version: "3"
services:
  postgres:
    image: postgres:13.2
    container_name: blog_db
    ports:
      - "4432:5432"
    environment:
      - POSTGRES_PASSWORD=secretpw
      - POSTGRES_USER=klaus
      - POSTGRES_DB=blog_db
    volumes:
      - ./init-project-db.sql:/docker-entrypoint-initdb.d/init-blog-db.sql
      - ./db-data:/var/lib/postgresql/data
